### ISSUE TITLE
Design the database schema

### ISSUE THREAD

**Issue by StephanNazarkin** [StephanNazarkin/Cinome#1]

**Comment by YuliiRunikov** [comment]
![mySql](https://user-images.githubusercontent.com/60647846/183179875-ffa2663a-679b-490f-b58d-cdea96bef1db.png)

**Comment by NMishchenko** [comment]
Can you rename TagItem (and Tag_value) according to the general schema naming convention? And remove unnecessary primary keys, please.

**Comment by AlexandrTsV** [comment]
Please make relations between tables more obvious. You can achieve that by drawing relations in addition to foreign keys. Also, I agree with Nikita.

**Comment by YuliiRunikov** [comment]
![database schema](https://user-images.githubusercontent.com/60647846/184687683-b7030960-6b4c-491b-9bc6-0b117b64ebfc.png)

**Comment by YuliiRunikov** [comment]
please remind me what should be renamed TagItem

**Comment by AlexandrTsV** [comment]
@YuliiRunikov tag_item, tag_value

**Comment by YuliiRunikov** [comment]
![database schema](https://user-images.githubusercontent.com/60647846/184702973-fad6a087-7bba-426d-9854-a8eedc23ceb2.png)

**Comment by YuliiRunikov** [comment]
![database schema](https://user-images.githubusercontent.com/60647846/184704173-6899c141-e240-44ae-bdd1-310e62dddc2d.png)

**Comment by NMishchenko** [comment]
Nice job! 🦾
