### ISSUE TITLE
Find or design and draw mockups

### ISSUE THREAD

**Issue by StephanNazarkin** [StephanNazarkin/Cinome#15]

**Comment by NMishchenko** [comment]
### Header as Guest
___
![Header as Guest](https://user-images.githubusercontent.com/86302509/181868589-14725d3e-0d5c-4bef-b420-51f3f4867e8d.png)

### Header as User
___
![Header as User](https://user-images.githubusercontent.com/86302509/181868626-d77773fd-69e5-45f2-9583-b3c3dfa9aae2.png)

### User search pop-up
___
<img src="https://user-images.githubusercontent.com/86302509/181870123-29304dbd-c79f-4d27-bdf6-8a7f66adaa1a.png" width="200" />

**Comment by NMishchenko** [comment]
### Elements catalog page
___
![Elements catalog page](https://user-images.githubusercontent.com/86302509/181870353-bdaaa023-933a-4cdb-a2c1-ac5177954055.png)

**Comment by NMishchenko** [comment]
### User profile page
___
![Profile page](https://user-images.githubusercontent.com/86302509/181870391-3a3afbe7-6235-450d-bc00-e09f342cd7b4.png)

### Information content
___
<img src="https://user-images.githubusercontent.com/86302509/181870388-13cdbcc6-03d9-49b8-9571-08dc18eb59a4.png" width="400" />

### Friends content
___
<img src="https://user-images.githubusercontent.com/86302509/181870392-a1ec8ed2-7c0c-4adb-aa5e-a6db0215412e.png" width="400" />

**Comment by NMishchenko** [comment]
### Element page
___
![Element page](https://user-images.githubusercontent.com/86302509/181870480-5ce3dc98-d81e-4d44-9502-32de66ff2488.png)

**Comment by NMishchenko** [comment]
### Registration page
___
![Registration page](https://user-images.githubusercontent.com/86302509/181870491-797209a2-365a-4ef9-8038-63c6fb20ae68.png)

### Login pop-up window
___
<img src="https://user-images.githubusercontent.com/86302509/181870492-c44623e1-0f62-46f7-98c8-d7e802789f3c.png" width="400" />

**Comment by vladimir-riabenko** [comment]
А профиль других Юзеров просматривать можно будет? Если да, то он будет выглядеть как "User profile page"?

**Comment by volodymyr-riabenko** [comment]
Will it be possible to visit profile of another user?

**Comment by NMishchenko** [comment]
Yes, it will. I've made a page for this case.

### Another user profile page
___
![Profile page](https://user-images.githubusercontent.com/86302509/181961209-dda342b5-5e60-4b29-807a-c2447537c9a6.png)

**Comment by AlexandrTsV** [comment]
Nice job.
