### ISSUE TITLE
Find out which controllers need to be implemented

### ISSUE THREAD

**Issue by StephanNazarkin** [StephanNazarkin/Cinome#2]

**Comment by vladimir-riabenko** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/76427828/181342469-f88e3f45-4504-489d-a5d7-9974881f943a.jpg)

**Comment by NMishchenko** [comment]
Please, add new methods according to the basic app functionality document.

**Comment by volodymyr-riabenko** [comment]
Where is this document?

**Comment by NMishchenko** [comment]
In the telegram chat.

**Comment by vladimir-riabenko** [comment]
![image](https://user-images.githubusercontent.com/76427828/182097202-8c882c10-5e71-460f-9fe8-97efe8dda117.png)

**Comment by vladimir-riabenko** [comment]
![image](https://user-images.githubusercontent.com/76427828/182097969-43bd6fa3-3878-4391-b413-605c5a66cd1a.png)

**Comment by vladimir-riabenko** [comment]
![image](https://user-images.githubusercontent.com/76427828/182220541-973d5f82-1db6-4eca-94ca-d60a14122c68.png)

**Comment by vladimir-riabenko** [comment]
![image](https://user-images.githubusercontent.com/76427828/182221350-9c8b5579-4ab0-481a-a58c-69a919cc8c26.png)

**Comment by vladimir-riabenko** [comment]
![image](https://user-images.githubusercontent.com/76427828/182226425-efda1bd8-c295-4a5c-a652-fd83378a8a63.png)

**Comment by volodymyr-riabenko** [comment]
![image](https://user-images.githubusercontent.com/76427828/182228614-34dafd6d-356d-4c56-950d-237b4ebbc7e0.png)
